# Generated by Django 4.0.1 on 2022-01-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fooldal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='szemely',
            options={'verbose_name_plural': 'Személyek'},
        ),
    ]
